# Generated by Django 4.0.3 on 2022-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_amoount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amoount',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
